language: cpp

sudo: false
dist: trusty

compiler:
  - gcc

    
script: 
  ############################################################################ 
  # Builds and tests 
  ############################################################################ 
  - mkdir -p build 
  - cd build 
  - cmake .. -DCMAKE_BUILD_TYPE=Release  
  - cmake --build . -- -j 
  - ctest 

